/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type MediaItemReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "mediaItem";
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Homepage = {
  _id: string;
  _type: "homepage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero: {
    eyebrow?: string;
    headline: string;
    subcopy?: string;
  };
  heroVideo?: MediaItemReference;
  bandIntro: {
    kicker?: string;
    heading: string;
    paragraphs: Array<string>;
    ctaLabel?: string;
  };
  featuredMedia?: Array<
    {
      _key: string;
    } & MediaItemReference
  >;
  testimonials?: Array<{
    quote: string;
    attribution: string;
    _type: "testimonial";
    _key: string;
  }>;
  bookingCta: {
    kicker?: string;
    heading: string;
    body: string;
    ctaLabel: string;
  };
  seo?: {
    metaTitle?: string;
    metaDescription?: string;
    ogImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type MediaItem = {
  _id: string;
  _type: "mediaItem";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  mediaType: "image" | "video";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt?: string;
  videoProvider?: "youtube" | "vimeo" | "other";
  videoUrl?: string;
  videoPoster?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Event = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  startDateTime: string;
  endDateTime?: string;
  status: "scheduled" | "cancelled" | "postponed";
  visibility: "public" | "busyOnly" | "hidden";
  title?: string;
  slug?: Slug;
  venue?: string;
  location?: string;
  description?: string;
  externalEventUrl?: string;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | MediaItemReference
  | SanityImageAssetReference
  | Homepage
  | SanityImageCrop
  | SanityImageHotspot
  | MediaItem
  | Event
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../web/src/sanity/queries.ts
// Variable: HOMEPAGE_QUERY
// Query: *[_type == "homepage" && _id == "homepage"][0]{    hero,    heroVideo->{ videoUrl, videoProvider },    bandIntro,    featuredMedia[]{      _key,      "mediaItem": @->{        _id,        title,        alt,        image{          ...,          asset->{            _id,            metadata{              dimensions            }          }        }      }    },    testimonials[]{ _key, quote, attribution },    bookingCta,    seo  }
export type HOMEPAGE_QUERY_RESULT = {
  hero: {
    eyebrow?: string;
    headline: string;
    subcopy?: string;
  };
  heroVideo: {
    videoUrl: string | null;
    videoProvider: "other" | "vimeo" | "youtube" | null;
  } | null;
  bandIntro: {
    kicker?: string;
    heading: string;
    paragraphs: Array<string>;
    ctaLabel?: string;
  };
  featuredMedia: Array<{
    _key: string;
    mediaItem: {
      _id: string;
      title: string;
      alt: string | null;
      image: {
        asset: {
          _id: string;
          metadata: {
            dimensions: SanityImageDimensions | null;
          } | null;
        } | null;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
    };
  }> | null;
  testimonials: Array<{
    _key: string;
    quote: string;
    attribution: string;
  }> | null;
  bookingCta: {
    kicker?: string;
    heading: string;
    body: string;
    ctaLabel: string;
  };
  seo: {
    metaTitle?: string;
    metaDescription?: string;
    ogImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  } | null;
} | null;

// Source: ../web/src/sanity/queries.ts
// Variable: UPCOMING_PUBLIC_EVENTS_QUERY
// Query: *[_type == "event"    && visibility == "public"    && status == "scheduled"    && coalesce(endDateTime, startDateTime) >= now()  ] | order(startDateTime asc) [0...3] {    _id, title, slug, startDateTime, endDateTime,    venue, location, externalEventUrl  }
export type UPCOMING_PUBLIC_EVENTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  startDateTime: string;
  endDateTime: string | null;
  venue: string | null;
  location: string | null;
  externalEventUrl: string | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "homepage" && _id == "homepage"][0]{\n    hero,\n    heroVideo->{ videoUrl, videoProvider },\n    bandIntro,\n    featuredMedia[]{\n      _key,\n      "mediaItem": @->{\n        _id,\n        title,\n        alt,\n        image{\n          ...,\n          asset->{\n            _id,\n            metadata{\n              dimensions\n            }\n          }\n        }\n      }\n    },\n    testimonials[]{ _key, quote, attribution },\n    bookingCta,\n    seo\n  }\n': HOMEPAGE_QUERY_RESULT;
    '\n  *[_type == "event"\n    && visibility == "public"\n    && status == "scheduled"\n    && coalesce(endDateTime, startDateTime) >= now()\n  ] | order(startDateTime asc) [0...3] {\n    _id, title, slug, startDateTime, endDateTime,\n    venue, location, externalEventUrl\n  }\n': UPCOMING_PUBLIC_EVENTS_QUERY_RESULT;
  }
}
