/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ShowsPage = {
  _id: string;
  _type: "showsPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  intro: {
    kicker?: string;
    heading: string;
    paragraphs: Array<string>;
  };
  upcoming: {
    heading: string;
  };
  recent: {
    kicker?: string;
    heading: string;
  };
  emptyState: {
    title: string;
    message: string;
    actionLabel: string;
  };
  bookingCta: {
    kicker?: string;
    heading: string;
    body: string;
    ctaLabel: string;
  };
  seo?: {
    metaTitle?: string;
    metaDescription?: string;
    ogImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type MediaItemReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "mediaItem";
};

export type BandMemberReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "bandMember";
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  intro: {
    kicker?: string;
    heading: string;
    lede: string;
    heroImage: MediaItemReference;
  };
  story: {
    kicker?: string;
    heading: string;
    paragraphs: Array<string>;
  };
  membersIntro: {
    kicker?: string;
    heading: string;
    body?: string;
  };
  members: Array<
    {
      _key: string;
    } & BandMemberReference
  >;
  experience: {
    kicker?: string;
    heading: string;
    introduction: string;
    highlights: Array<{
      title: string;
      description: string;
      _type: "experienceHighlight";
      _key: string;
    }>;
  };
  testimonialsIntro: {
    kicker: string;
    heading: string;
  };
  bookingCta: {
    kicker?: string;
    heading: string;
    body: string;
    ctaLabel: string;
  };
  seo?: {
    metaTitle?: string;
    metaDescription?: string;
    ogImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  };
};

export type Homepage = {
  _id: string;
  _type: "homepage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero: {
    eyebrow?: string;
    headline: string;
    subcopy?: string;
  };
  heroVideo?: MediaItemReference;
  bandIntro: {
    kicker?: string;
    heading: string;
    paragraphs: Array<string>;
    ctaLabel?: string;
  };
  featuredMedia?: Array<
    {
      _key: string;
    } & MediaItemReference
  >;
  galleryIntro: {
    kicker: string;
    heading: string;
    ctaLabel: string;
  };
  upcomingShows: {
    kicker: string;
    heading: string;
    viewAllLabel: string;
    emptyState: {
      title: string;
      message: string;
      actionLabel: string;
    };
  };
  testimonialsIntro: {
    kicker: string;
    heading: string;
  };
  bookingCta: {
    kicker?: string;
    heading: string;
    body: string;
    ctaLabel: string;
  };
  seo?: {
    metaTitle?: string;
    metaDescription?: string;
    ogImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  };
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  quote: string;
  sourceName: string;
  sourceContext?: string;
  sourceLogo?: MediaItemReference;
  sourceUrl?: string;
  displayOrder: number;
};

export type BandMember = {
  _id: string;
  _type: "bandMember";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  role: string;
  profileImage: MediaItemReference;
  biography: Array<string>;
  publicLinks?: Array<{
    linkType:
      "instagram" | "facebook" | "youtube" | "spotify" | "website" | "other";
    label?: string;
    url: string;
    _type: "publicLink";
    _key: string;
  }>;
};

export type MediaItem = {
  _id: string;
  _type: "mediaItem";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  mediaType: "image" | "video";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt?: string;
  videoProvider?: "youtube" | "vimeo" | "other";
  videoUrl?: string;
  videoPoster?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Event = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  startDateTime: string;
  endDateTime?: string;
  status: "scheduled" | "cancelled" | "postponed";
  visibility: "public" | "busyOnly" | "hidden";
  title?: string;
  slug?: Slug;
  venue?: string;
  location?: string;
  description?: string;
  externalEventUrl?: string;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | ShowsPage
  | SanityImageCrop
  | SanityImageHotspot
  | MediaItemReference
  | BandMemberReference
  | AboutPage
  | Homepage
  | Testimonial
  | BandMember
  | MediaItem
  | Event
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../web/src/sanity/queries.ts
// Variable: HOMEPAGE_QUERY
// Query: *[_type == "homepage" && _id == "homepage"][0]{    hero,    heroVideo->{ videoUrl, videoProvider },    bandIntro,    featuredMedia[]{      _key,      "mediaItem": @->{        _id,        title,        alt,        image{          ...,          asset->{            _id,            metadata{              dimensions            }          }        }      }    },    upcomingShows{      kicker,      heading,      viewAllLabel,      emptyState{ title, message, actionLabel }    },    galleryIntro{ kicker, heading, ctaLabel },    testimonialsIntro{ kicker, heading },    bookingCta,    seo  }
export type HOMEPAGE_QUERY_RESULT = {
  hero: {
    eyebrow?: string;
    headline: string;
    subcopy?: string;
  };
  heroVideo: {
    videoUrl: string | null;
    videoProvider: "other" | "vimeo" | "youtube" | null;
  } | null;
  bandIntro: {
    kicker?: string;
    heading: string;
    paragraphs: Array<string>;
    ctaLabel?: string;
  };
  featuredMedia: Array<{
    _key: string;
    mediaItem: {
      _id: string;
      title: string;
      alt: string | null;
      image: {
        asset: {
          _id: string;
          metadata: {
            dimensions: SanityImageDimensions | null;
          } | null;
        } | null;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
    };
  }> | null;
  upcomingShows: {
    kicker: string;
    heading: string;
    viewAllLabel: string;
    emptyState: {
      title: string;
      message: string;
      actionLabel: string;
    };
  };
  galleryIntro: {
    kicker: string;
    heading: string;
    ctaLabel: string;
  };
  testimonialsIntro: {
    kicker: string;
    heading: string;
  };
  bookingCta: {
    kicker?: string;
    heading: string;
    body: string;
    ctaLabel: string;
  };
  seo: {
    metaTitle?: string;
    metaDescription?: string;
    ogImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  } | null;
} | null;

// Source: ../web/src/sanity/queries.ts
// Variable: TESTIMONIALS_QUERY
// Query: *[_type == "testimonial"]  | order(displayOrder asc, _id asc)[0...3] {    _id,    quote,    sourceName,    sourceContext,    sourceUrl,    displayOrder,    sourceLogo->{      _id,      title,      alt,      image{        ...,        asset->{          _id,          metadata{ dimensions }        }      }    }  }
export type TESTIMONIALS_QUERY_RESULT = Array<{
  _id: string;
  quote: string;
  sourceName: string;
  sourceContext: string | null;
  sourceUrl: string | null;
  displayOrder: number;
  sourceLogo: {
    _id: string;
    title: string;
    alt: string | null;
    image: {
      asset: {
        _id: string;
        metadata: {
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
}>;

// Source: ../web/src/sanity/queries.ts
// Variable: ABOUT_PAGE_QUERY
// Query: *[_type == "aboutPage" && _id == "aboutPage"][0]{    intro{      kicker,      heading,      lede,      heroImage->{        _id,        title,        alt,        image{          ...,          asset->{            _id,            metadata{ dimensions }          }        }      }    },    story{ kicker, heading, paragraphs },    membersIntro{ kicker, heading, body },    members[]{      _key,      "member": @->{        _id,        name,        role,        profileImage->{          _id,          title,          alt,          image{            ...,            asset->{              _id,              metadata{ dimensions }            }          }        },        biography,        publicLinks[]{ _key, linkType, label, url }      }    },    experience{      kicker,      heading,      introduction,      highlights[]{ _key, title, description }    },    testimonialsIntro{ kicker, heading },    bookingCta{ kicker, heading, body, ctaLabel },    seo{ metaTitle, metaDescription, ogImage }  }
export type ABOUT_PAGE_QUERY_RESULT = {
  intro: {
    kicker: string | null;
    heading: string;
    lede: string;
    heroImage: {
      _id: string;
      title: string;
      alt: string | null;
      image: {
        asset: {
          _id: string;
          metadata: {
            dimensions: SanityImageDimensions | null;
          } | null;
        } | null;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
    };
  };
  story: {
    kicker: string | null;
    heading: string;
    paragraphs: Array<string>;
  };
  membersIntro: {
    kicker: string | null;
    heading: string;
    body: string | null;
  };
  members: Array<{
    _key: string;
    member: {
      _id: string;
      name: string;
      role: string;
      profileImage: {
        _id: string;
        title: string;
        alt: string | null;
        image: {
          asset: {
            _id: string;
            metadata: {
              dimensions: SanityImageDimensions | null;
            } | null;
          } | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
      };
      biography: Array<string>;
      publicLinks: Array<{
        _key: string;
        linkType:
          | "facebook"
          | "instagram"
          | "other"
          | "spotify"
          | "website"
          | "youtube";
        label: string | null;
        url: string;
      }> | null;
    };
  }>;
  experience: {
    kicker: string | null;
    heading: string;
    introduction: string;
    highlights: Array<{
      _key: string;
      title: string;
      description: string;
    }>;
  };
  testimonialsIntro: {
    kicker: string;
    heading: string;
  };
  bookingCta: {
    kicker: string | null;
    heading: string;
    body: string;
    ctaLabel: string;
  };
  seo: {
    metaTitle: string | null;
    metaDescription: string | null;
    ogImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
} | null;

// Source: ../web/src/sanity/queries.ts
// Variable: UPCOMING_PUBLIC_EVENTS_QUERY
// Query: *[_type == "event"    && visibility == "public"    && status == "scheduled"    && coalesce(endDateTime, startDateTime) >= now()  ] | order(startDateTime asc) [0...3] {    _id, title, slug, startDateTime, endDateTime,    venue, location, externalEventUrl  }
export type UPCOMING_PUBLIC_EVENTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  startDateTime: string;
  endDateTime: string | null;
  venue: string | null;
  location: string | null;
  externalEventUrl: string | null;
}>;

// Source: ../web/src/sanity/queries.ts
// Variable: SHOWS_PAGE_QUERY
// Query: *[_type == "showsPage" && _id == "showsPage"][0]{    intro{ kicker, heading, paragraphs },    upcoming{ heading },    recent{ kicker, heading },    emptyState{ title, message, actionLabel },    bookingCta{ kicker, heading, body, ctaLabel },    seo{ metaTitle, metaDescription, ogImage }  }
export type SHOWS_PAGE_QUERY_RESULT = {
  intro: {
    kicker: string | null;
    heading: string;
    paragraphs: Array<string>;
  };
  upcoming: {
    heading: string;
  };
  recent: {
    kicker: string | null;
    heading: string;
  };
  emptyState: {
    title: string;
    message: string;
    actionLabel: string;
  };
  bookingCta: {
    kicker: string | null;
    heading: string;
    body: string;
    ctaLabel: string;
  };
  seo: {
    metaTitle: string | null;
    metaDescription: string | null;
    ogImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
} | null;

// Source: ../web/src/sanity/queries.ts
// Variable: SHOWS_UPCOMING_PUBLIC_EVENTS_QUERY
// Query: *[    _type == "event"    && visibility == "public"    && defined(startDateTime)    && coalesce(endDateTime, startDateTime) >= now()  ]  | order(startDateTime asc, _id asc) {    _id,    "kind": "public",    status,    startDateTime,    endDateTime,    title,    venue,    location,    description,    externalEventUrl  }
export type SHOWS_UPCOMING_PUBLIC_EVENTS_QUERY_RESULT = Array<{
  _id: string;
  kind: "public";
  status: "cancelled" | "postponed" | "scheduled";
  startDateTime: string;
  endDateTime: string | null;
  title: string | null;
  venue: string | null;
  location: string | null;
  description: string | null;
  externalEventUrl: string | null;
}>;

// Source: ../web/src/sanity/queries.ts
// Variable: SHOWS_UPCOMING_PRIVATE_EVENTS_QUERY
// Query: *[    _type == "event"    && visibility == "busyOnly"    && status == "scheduled"    && defined(startDateTime)    && coalesce(endDateTime, startDateTime) >= now()  ]  | order(startDateTime asc, _id asc) {    _id,    "kind": "private",    startDateTime,    endDateTime  }
export type SHOWS_UPCOMING_PRIVATE_EVENTS_QUERY_RESULT = Array<{
  _id: string;
  kind: "private";
  startDateTime: string;
  endDateTime: string | null;
}>;

// Source: ../web/src/sanity/queries.ts
// Variable: SHOWS_RECENT_PUBLIC_EVENTS_QUERY
// Query: *[    _type == "event"    && visibility == "public"    && status == "scheduled"    && defined(startDateTime)    && coalesce(endDateTime, startDateTime) < now()  ]  | order(startDateTime desc, _id asc) [0...12] {    _id,    "kind": "public",    status,    startDateTime,    endDateTime,    title,    venue,    location,    description,    externalEventUrl  }
export type SHOWS_RECENT_PUBLIC_EVENTS_QUERY_RESULT = Array<{
  _id: string;
  kind: "public";
  status: "cancelled" | "postponed" | "scheduled";
  startDateTime: string;
  endDateTime: string | null;
  title: string | null;
  venue: string | null;
  location: string | null;
  description: string | null;
  externalEventUrl: string | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "homepage" && _id == "homepage"][0]{\n    hero,\n    heroVideo->{ videoUrl, videoProvider },\n    bandIntro,\n    featuredMedia[]{\n      _key,\n      "mediaItem": @->{\n        _id,\n        title,\n        alt,\n        image{\n          ...,\n          asset->{\n            _id,\n            metadata{\n              dimensions\n            }\n          }\n        }\n      }\n    },\n    upcomingShows{\n      kicker,\n      heading,\n      viewAllLabel,\n      emptyState{ title, message, actionLabel }\n    },\n    galleryIntro{ kicker, heading, ctaLabel },\n    testimonialsIntro{ kicker, heading },\n    bookingCta,\n    seo\n  }\n': HOMEPAGE_QUERY_RESULT;
    '\n  *[_type == "testimonial"]\n  | order(displayOrder asc, _id asc)[0...3] {\n    _id,\n    quote,\n    sourceName,\n    sourceContext,\n    sourceUrl,\n    displayOrder,\n    sourceLogo->{\n      _id,\n      title,\n      alt,\n      image{\n        ...,\n        asset->{\n          _id,\n          metadata{ dimensions }\n        }\n      }\n    }\n  }\n': TESTIMONIALS_QUERY_RESULT;
    '\n  *[_type == "aboutPage" && _id == "aboutPage"][0]{\n    intro{\n      kicker,\n      heading,\n      lede,\n      heroImage->{\n        _id,\n        title,\n        alt,\n        image{\n          ...,\n          asset->{\n            _id,\n            metadata{ dimensions }\n          }\n        }\n      }\n    },\n    story{ kicker, heading, paragraphs },\n    membersIntro{ kicker, heading, body },\n    members[]{\n      _key,\n      "member": @->{\n        _id,\n        name,\n        role,\n        profileImage->{\n          _id,\n          title,\n          alt,\n          image{\n            ...,\n            asset->{\n              _id,\n              metadata{ dimensions }\n            }\n          }\n        },\n        biography,\n        publicLinks[]{ _key, linkType, label, url }\n      }\n    },\n    experience{\n      kicker,\n      heading,\n      introduction,\n      highlights[]{ _key, title, description }\n    },\n    testimonialsIntro{ kicker, heading },\n    bookingCta{ kicker, heading, body, ctaLabel },\n    seo{ metaTitle, metaDescription, ogImage }\n  }\n': ABOUT_PAGE_QUERY_RESULT;
    '\n  *[_type == "event"\n    && visibility == "public"\n    && status == "scheduled"\n    && coalesce(endDateTime, startDateTime) >= now()\n  ] | order(startDateTime asc) [0...3] {\n    _id, title, slug, startDateTime, endDateTime,\n    venue, location, externalEventUrl\n  }\n': UPCOMING_PUBLIC_EVENTS_QUERY_RESULT;
    '\n  *[_type == "showsPage" && _id == "showsPage"][0]{\n    intro{ kicker, heading, paragraphs },\n    upcoming{ heading },\n    recent{ kicker, heading },\n    emptyState{ title, message, actionLabel },\n    bookingCta{ kicker, heading, body, ctaLabel },\n    seo{ metaTitle, metaDescription, ogImage }\n  }\n': SHOWS_PAGE_QUERY_RESULT;
    '\n  *[\n    _type == "event"\n    && visibility == "public"\n    && defined(startDateTime)\n    && coalesce(endDateTime, startDateTime) >= now()\n  ]\n  | order(startDateTime asc, _id asc) {\n    _id,\n    "kind": "public",\n    status,\n    startDateTime,\n    endDateTime,\n    title,\n    venue,\n    location,\n    description,\n    externalEventUrl\n  }\n': SHOWS_UPCOMING_PUBLIC_EVENTS_QUERY_RESULT;
    '\n  *[\n    _type == "event"\n    && visibility == "busyOnly"\n    && status == "scheduled"\n    && defined(startDateTime)\n    && coalesce(endDateTime, startDateTime) >= now()\n  ]\n  | order(startDateTime asc, _id asc) {\n    _id,\n    "kind": "private",\n    startDateTime,\n    endDateTime\n  }\n': SHOWS_UPCOMING_PRIVATE_EVENTS_QUERY_RESULT;
    '\n  *[\n    _type == "event"\n    && visibility == "public"\n    && status == "scheduled"\n    && defined(startDateTime)\n    && coalesce(endDateTime, startDateTime) < now()\n  ]\n  | order(startDateTime desc, _id asc) [0...12] {\n    _id,\n    "kind": "public",\n    status,\n    startDateTime,\n    endDateTime,\n    title,\n    venue,\n    location,\n    description,\n    externalEventUrl\n  }\n': SHOWS_RECENT_PUBLIC_EVENTS_QUERY_RESULT;
  }
}
