/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type MediaItemReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "mediaItem";
};

export type MusicReleaseReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "musicRelease";
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type MusicPage = {
  _id: string;
  _type: "musicPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  featured: {
    kicker?: string;
    heading: string;
    video?: MediaItemReference;
  };
  labelAffiliation?: {
    kicker?: string;
    text: string;
    logoAlt: string;
    url: string;
    missionStatement: string;
    socialLinks?: {
      facebookUrl: string;
      instagramUrl: string;
      youtubeUrl: string;
    };
  };
  releases?: Array<
    {
      _key: string;
    } & MusicReleaseReference
  >;
  seo?: {
    metaTitle?: string;
    metaDescription?: string;
    ogImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type ContactPage = {
  _id: string;
  _type: "contactPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  intro: {
    kicker?: string;
    heading: string;
    lede: string;
    explanation: string;
  };
  newsletterCta: {
    heading: string;
    body: string;
    linkLabel: string;
  };
  faq?: Array<{
    question: string;
    answer: string;
    _type: "faqEntry";
    _key: string;
  }>;
  seo?: {
    metaTitle?: string;
    metaDescription?: string;
    ogImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  };
};

export type MerchItemReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "merchItem";
};

export type GalleryPage = {
  _id: string;
  _type: "galleryPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  gallery: {
    kicker?: string;
    heading: string;
    body?: string;
    items?: Array<
      {
        _key: string;
      } & MediaItemReference
    >;
    videos?: Array<
      {
        _key: string;
      } & MediaItemReference
    >;
  };
  eventMediaSubmission?: {
    enabled?: boolean;
    kicker?: string;
    heading?: string;
    explanation?: string;
    ctaLabel?: string;
    formUrl?: string;
  };
  merch: {
    kicker?: string;
    heading: string;
    body?: string;
    items?: Array<
      {
        _key: string;
      } & MerchItemReference
    >;
  };
  bookingCta: {
    kicker?: string;
    heading: string;
    body: string;
    ctaLabel: string;
  };
  seo?: {
    metaTitle?: string;
    metaDescription?: string;
    ogImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  };
};

export type ShowsPage = {
  _id: string;
  _type: "showsPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  intro: {
    kicker?: string;
    heading: string;
    paragraphs: Array<string>;
  };
  upcoming: {
    heading: string;
  };
  recent: {
    kicker?: string;
    heading: string;
  };
  emptyState: {
    title: string;
    message: string;
    actionLabel: string;
  };
  bookingCta: {
    kicker?: string;
    heading: string;
    body: string;
    ctaLabel: string;
  };
  seo?: {
    metaTitle?: string;
    metaDescription?: string;
    ogImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  };
};

export type BandMemberReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "bandMember";
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  intro: {
    kicker?: string;
    heading: string;
    paragraphs: Array<string>;
    heroImage: MediaItemReference;
  };
  membersIntro: {
    kicker?: string;
    heading: string;
    body?: string;
  };
  members: Array<
    {
      _key: string;
    } & BandMemberReference
  >;
  testimonialsIntro: {
    kicker: string;
    heading: string;
  };
  bookingCta: {
    kicker?: string;
    heading: string;
    body: string;
    ctaLabel: string;
  };
  seo?: {
    metaTitle?: string;
    metaDescription?: string;
    ogImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  };
};

export type Homepage = {
  _id: string;
  _type: "homepage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero: {
    eyebrow?: string;
    headline: string;
    subcopy?: string;
  };
  heroVideo?: MediaItemReference;
  officialBandPhotos?: {
    kicker?: string;
    heading: string;
    body?: string;
    ctaLabel: string;
    photos?: Array<
      {
        _key: string;
      } & MediaItemReference
    >;
  };
  experience: {
    kicker?: string;
    heading: string;
    introduction: string;
    highlights: Array<{
      title: string;
      description: string;
      _type: "experienceHighlight";
      _key: string;
    }>;
  };
  upcomingShows: {
    kicker: string;
    heading: string;
    viewAllLabel: string;
    emptyState: {
      title: string;
      message: string;
      actionLabel: string;
    };
  };
  testimonialsIntro: {
    kicker: string;
    heading: string;
  };
  bookingCta: {
    kicker?: string;
    heading: string;
    body: string;
    ctaLabel: string;
  };
  newsletter: {
    kicker?: string;
    heading: string;
    body: string;
    ctaLabel: string;
  };
  seo?: {
    metaTitle?: string;
    metaDescription?: string;
    ogImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  };
};

export type MusicRelease = {
  _id: string;
  _type: "musicRelease";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug?: Slug;
  releaseType?: "single" | "ep" | "album" | "other";
  state: "upcoming" | "released";
  releaseDate: string;
  coverArtwork?: MediaItemReference;
  description?: string;
  spotifyUrl?: string;
  appleMusicUrl?: string;
  preSaveUrl?: string;
  watchVideoUrl?: string;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type MerchItem = {
  _id: string;
  _type: "merchItem";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  description: string;
  image?: MediaItemReference;
  priceDisplay?: string;
  availabilityNote?: string;
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  quote: string;
  sourceName: string;
  sourceContext?: string;
  sourceLogo?: MediaItemReference;
  sourceUrl?: string;
  displayOrder: number;
};

export type BandMember = {
  _id: string;
  _type: "bandMember";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  role: string;
  profileImage: MediaItemReference;
  biography: Array<string>;
  publicLinks?: Array<{
    linkType:
      "instagram" | "facebook" | "youtube" | "spotify" | "website" | "other";
    label?: string;
    url: string;
    _type: "publicLink";
    _key: string;
  }>;
};

export type MediaItem = {
  _id: string;
  _type: "mediaItem";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  mediaType: "image" | "video";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt?: string;
  videoProvider?: "youtube" | "vimeo" | "other";
  videoUrl?: string;
  videoPoster?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  category?: "performance" | "venue-crowd";
  creditLine?: string;
  creditUrl?: string;
};

export type Event = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  startDateTime: string;
  endDateTime?: string;
  status: "scheduled" | "cancelled" | "postponed";
  visibility: "public" | "busyOnly" | "hidden";
  title?: string;
  slug?: Slug;
  venue?: string;
  location?: string;
  description?: string;
  externalEventUrl?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | MediaItemReference
  | MusicReleaseReference
  | SanityImageAssetReference
  | MusicPage
  | SanityImageCrop
  | SanityImageHotspot
  | ContactPage
  | MerchItemReference
  | GalleryPage
  | ShowsPage
  | BandMemberReference
  | AboutPage
  | Homepage
  | MusicRelease
  | Slug
  | MerchItem
  | Testimonial
  | BandMember
  | MediaItem
  | Event
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../web/src/sanity/queries.ts
// Variable: HOMEPAGE_QUERY
// Query: *[_type == "homepage" && _id == "homepage"][0]{    hero,    heroVideo->{ videoUrl, videoProvider, title },    officialBandPhotos{      kicker,      heading,      body,      ctaLabel,      photos[]{        _key,        "mediaItem": @->{          _id,          title,          alt,          creditLine,          creditUrl,          image{            ...,            asset->{              _id,              metadata{ dimensions }            }          }        }      }    },    experience{      kicker,      heading,      introduction,      highlights[]{ _key, title, description }    },    upcomingShows{      kicker,      heading,      viewAllLabel,      emptyState{ title, message, actionLabel }    },    testimonialsIntro{ kicker, heading },    bookingCta,    newsletter{ kicker, heading, body, ctaLabel },    seo  }
export type HOMEPAGE_QUERY_RESULT = {
  hero: {
    eyebrow?: string;
    headline: string;
    subcopy?: string;
  };
  heroVideo: {
    videoUrl: string | null;
    videoProvider: "other" | "vimeo" | "youtube" | null;
    title: string;
  } | null;
  officialBandPhotos: {
    kicker: string | null;
    heading: string;
    body: string | null;
    ctaLabel: string;
    photos: Array<{
      _key: string;
      mediaItem: {
        _id: string;
        title: string;
        alt: string | null;
        creditLine: string | null;
        creditUrl: string | null;
        image: {
          asset: {
            _id: string;
            metadata: {
              dimensions: SanityImageDimensions | null;
            } | null;
          } | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
      };
    }> | null;
  } | null;
  experience: {
    kicker: string | null;
    heading: string;
    introduction: string;
    highlights: Array<{
      _key: string;
      title: string;
      description: string;
    }>;
  };
  upcomingShows: {
    kicker: string;
    heading: string;
    viewAllLabel: string;
    emptyState: {
      title: string;
      message: string;
      actionLabel: string;
    };
  };
  testimonialsIntro: {
    kicker: string;
    heading: string;
  };
  bookingCta: {
    kicker?: string;
    heading: string;
    body: string;
    ctaLabel: string;
  };
  newsletter: {
    kicker: string | null;
    heading: string;
    body: string;
    ctaLabel: string;
  };
  seo: {
    metaTitle?: string;
    metaDescription?: string;
    ogImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  } | null;
} | null;

// Source: ../web/src/sanity/queries.ts
// Variable: TESTIMONIALS_QUERY
// Query: *[_type == "testimonial"]  | order(displayOrder asc, _id asc)[0...3] {    _id,    quote,    sourceName,    sourceContext,    sourceUrl,    displayOrder,    sourceLogo->{      _id,      title,      alt,      image{        ...,        asset->{          _id,          metadata{ dimensions }        }      }    }  }
export type TESTIMONIALS_QUERY_RESULT = Array<{
  _id: string;
  quote: string;
  sourceName: string;
  sourceContext: string | null;
  sourceUrl: string | null;
  displayOrder: number;
  sourceLogo: {
    _id: string;
    title: string;
    alt: string | null;
    image: {
      asset: {
        _id: string;
        metadata: {
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
}>;

// Source: ../web/src/sanity/queries.ts
// Variable: ABOUT_PAGE_QUERY
// Query: *[_type == "aboutPage" && _id == "aboutPage"][0]{    intro{      kicker,      heading,      paragraphs,      heroImage->{        _id,        title,        alt,        image{          ...,          asset->{            _id,            metadata{ dimensions }          }        }      }    },    membersIntro{ kicker, heading, body },    members[]{      _key,      "member": @->{        _id,        name,        role,        profileImage->{          _id,          title,          alt,          image{            ...,            asset->{              _id,              metadata{ dimensions }            }          }        },        biography,        publicLinks[]{ _key, linkType, label, url }      }    },    testimonialsIntro{ kicker, heading },    bookingCta{ kicker, heading, body, ctaLabel },    seo{ metaTitle, metaDescription, ogImage }  }
export type ABOUT_PAGE_QUERY_RESULT = {
  intro: {
    kicker: string | null;
    heading: string;
    paragraphs: Array<string>;
    heroImage: {
      _id: string;
      title: string;
      alt: string | null;
      image: {
        asset: {
          _id: string;
          metadata: {
            dimensions: SanityImageDimensions | null;
          } | null;
        } | null;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
    };
  };
  membersIntro: {
    kicker: string | null;
    heading: string;
    body: string | null;
  };
  members: Array<{
    _key: string;
    member: {
      _id: string;
      name: string;
      role: string;
      profileImage: {
        _id: string;
        title: string;
        alt: string | null;
        image: {
          asset: {
            _id: string;
            metadata: {
              dimensions: SanityImageDimensions | null;
            } | null;
          } | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
      };
      biography: Array<string>;
      publicLinks: Array<{
        _key: string;
        linkType:
          | "facebook"
          | "instagram"
          | "other"
          | "spotify"
          | "website"
          | "youtube";
        label: string | null;
        url: string;
      }> | null;
    };
  }>;
  testimonialsIntro: {
    kicker: string;
    heading: string;
  };
  bookingCta: {
    kicker: string | null;
    heading: string;
    body: string;
    ctaLabel: string;
  };
  seo: {
    metaTitle: string | null;
    metaDescription: string | null;
    ogImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
} | null;

// Source: ../web/src/sanity/queries.ts
// Variable: UPCOMING_PUBLIC_EVENTS_QUERY
// Query: *[_type == "event"    && visibility == "public"    && status == "scheduled"    && coalesce(endDateTime, startDateTime) >= now()  ] | order(startDateTime asc) [0...3] {    _id, title, slug, startDateTime, endDateTime,    venue, location, externalEventUrl  }
export type UPCOMING_PUBLIC_EVENTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  startDateTime: string;
  endDateTime: string | null;
  venue: string | null;
  location: string | null;
  externalEventUrl: string | null;
}>;

// Source: ../web/src/sanity/queries.ts
// Variable: SHOWS_PAGE_QUERY
// Query: *[_type == "showsPage" && _id == "showsPage"][0]{    intro{ kicker, heading, paragraphs },    upcoming{ heading },    recent{ kicker, heading },    emptyState{ title, message, actionLabel },    bookingCta{ kicker, heading, body, ctaLabel },    seo{ metaTitle, metaDescription, ogImage }  }
export type SHOWS_PAGE_QUERY_RESULT = {
  intro: {
    kicker: string | null;
    heading: string;
    paragraphs: Array<string>;
  };
  upcoming: {
    heading: string;
  };
  recent: {
    kicker: string | null;
    heading: string;
  };
  emptyState: {
    title: string;
    message: string;
    actionLabel: string;
  };
  bookingCta: {
    kicker: string | null;
    heading: string;
    body: string;
    ctaLabel: string;
  };
  seo: {
    metaTitle: string | null;
    metaDescription: string | null;
    ogImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
} | null;

// Source: ../web/src/sanity/queries.ts
// Variable: SHOWS_UPCOMING_PUBLIC_EVENTS_QUERY
// Query: *[    _type == "event"    && visibility == "public"    && defined(startDateTime)    && coalesce(endDateTime, startDateTime) >= now()  ]  | order(startDateTime asc, _id asc) {    _id,    "kind": "public",    status,    startDateTime,    endDateTime,    title,    venue,    location,    description,    externalEventUrl  }
export type SHOWS_UPCOMING_PUBLIC_EVENTS_QUERY_RESULT = Array<{
  _id: string;
  kind: "public";
  status: "cancelled" | "postponed" | "scheduled";
  startDateTime: string;
  endDateTime: string | null;
  title: string | null;
  venue: string | null;
  location: string | null;
  description: string | null;
  externalEventUrl: string | null;
}>;

// Source: ../web/src/sanity/queries.ts
// Variable: SHOWS_UPCOMING_PRIVATE_EVENTS_QUERY
// Query: *[    _type == "event"    && visibility == "busyOnly"    && status == "scheduled"    && defined(startDateTime)    && coalesce(endDateTime, startDateTime) >= now()  ]  | order(startDateTime asc, _id asc) {    _id,    "kind": "private",    startDateTime,    endDateTime  }
export type SHOWS_UPCOMING_PRIVATE_EVENTS_QUERY_RESULT = Array<{
  _id: string;
  kind: "private";
  startDateTime: string;
  endDateTime: string | null;
}>;

// Source: ../web/src/sanity/queries.ts
// Variable: SHOWS_RECENT_PUBLIC_EVENTS_QUERY
// Query: *[    _type == "event"    && visibility == "public"    && status == "scheduled"    && defined(startDateTime)    && coalesce(endDateTime, startDateTime) < now()  ]  | order(startDateTime desc, _id asc) [0...12] {    _id,    "kind": "public",    status,    startDateTime,    endDateTime,    title,    venue,    location,    description,    externalEventUrl  }
export type SHOWS_RECENT_PUBLIC_EVENTS_QUERY_RESULT = Array<{
  _id: string;
  kind: "public";
  status: "cancelled" | "postponed" | "scheduled";
  startDateTime: string;
  endDateTime: string | null;
  title: string | null;
  venue: string | null;
  location: string | null;
  description: string | null;
  externalEventUrl: string | null;
}>;

// Source: ../web/src/sanity/queries.ts
// Variable: CONTACT_PAGE_QUERY
// Query: *[_type == "contactPage" && _id == "contactPage"][0]{    intro{ kicker, heading, lede, explanation },    newsletterCta{ heading, body, linkLabel },    faq[]{ _key, question, answer },    seo{ metaTitle, metaDescription, ogImage }  }
export type CONTACT_PAGE_QUERY_RESULT = {
  intro: {
    kicker: string | null;
    heading: string;
    lede: string;
    explanation: string;
  };
  newsletterCta: {
    heading: string;
    body: string;
    linkLabel: string;
  };
  faq: Array<{
    _key: string;
    question: string;
    answer: string;
  }> | null;
  seo: {
    metaTitle: string | null;
    metaDescription: string | null;
    ogImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
} | null;

// Source: ../web/src/sanity/queries.ts
// Variable: MUSIC_PAGE_QUERY
// Query: *[_type == "musicPage" && _id == "musicPage"][0]{    featured{      kicker,      heading,      video->{        videoUrl,        videoProvider,        title      }    },    labelAffiliation{      kicker,      text,      logoAlt,      url,      missionStatement,      socialLinks{ facebookUrl, instagramUrl, youtubeUrl }    },    releases[]{      _key,      "release": @->{        _id,        title,        "slug": slug.current,        releaseType,        state,        releaseDate,        coverArtwork->{          _id,          alt,          image{            ...,            asset->{              _id,              metadata{ dimensions }            }          }        },        description,        spotifyUrl,        appleMusicUrl,        preSaveUrl,        watchVideoUrl      }    },    seo{ metaTitle, metaDescription, ogImage }  }
export type MUSIC_PAGE_QUERY_RESULT = {
  featured: {
    kicker: string | null;
    heading: string;
    video: {
      videoUrl: string | null;
      videoProvider: "other" | "vimeo" | "youtube" | null;
      title: string;
    } | null;
  };
  labelAffiliation: {
    kicker: string | null;
    text: string;
    logoAlt: string;
    url: string;
    missionStatement: string;
    socialLinks: {
      facebookUrl: string;
      instagramUrl: string;
      youtubeUrl: string;
    } | null;
  } | null;
  releases: Array<{
    _key: string;
    release: {
      _id: string;
      title: string;
      slug: string | null;
      releaseType: "album" | "ep" | "other" | "single" | null;
      state: "released" | "upcoming";
      releaseDate: string;
      coverArtwork: {
        _id: string;
        alt: string | null;
        image: {
          asset: {
            _id: string;
            metadata: {
              dimensions: SanityImageDimensions | null;
            } | null;
          } | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
      } | null;
      description: string | null;
      spotifyUrl: string | null;
      appleMusicUrl: string | null;
      preSaveUrl: string | null;
      watchVideoUrl: string | null;
    };
  }> | null;
  seo: {
    metaTitle: string | null;
    metaDescription: string | null;
    ogImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
} | null;

// Source: ../web/src/sanity/queries.ts
// Variable: GALLERY_PAGE_QUERY
// Query: *[_type == "galleryPage" && _id == "galleryPage"][0]{    gallery{      kicker,      heading,      body,      items[]{        _key,        "media": @->{          _id,          title,          alt,          category,          creditLine,          creditUrl,          image{            ...,            asset->{              _id,              metadata{ dimensions }            }          }        }      },      videos[]{        _key,        "media": @->{          _id,          title,          mediaType,          videoProvider,          videoUrl,          videoPoster{            ...,            asset->{              _id,              metadata{ dimensions }            }          },          creditLine,          creditUrl        }      }    },    eventMediaSubmission{      enabled,      kicker,      heading,      explanation,      ctaLabel,      formUrl    },    merch{      kicker,      heading,      body,      items[]{        _key,        "item": @->{          _id,          name,          description,          priceDisplay,          availabilityNote,          image->{            _id,            title,            alt,            image{              ...,              asset->{                _id,                metadata{ dimensions }              }            }          }        }      }    },    bookingCta{ kicker, heading, body, ctaLabel },    seo{ metaTitle, metaDescription, ogImage }  }
export type GALLERY_PAGE_QUERY_RESULT = {
  gallery: {
    kicker: string | null;
    heading: string;
    body: string | null;
    items: Array<{
      _key: string;
      media: {
        _id: string;
        title: string;
        alt: string | null;
        category: "performance" | "venue-crowd" | null;
        creditLine: string | null;
        creditUrl: string | null;
        image: {
          asset: {
            _id: string;
            metadata: {
              dimensions: SanityImageDimensions | null;
            } | null;
          } | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
      };
    }> | null;
    videos: Array<{
      _key: string;
      media: {
        _id: string;
        title: string;
        mediaType: "image" | "video";
        videoProvider: "other" | "vimeo" | "youtube" | null;
        videoUrl: string | null;
        videoPoster: {
          asset: {
            _id: string;
            metadata: {
              dimensions: SanityImageDimensions | null;
            } | null;
          } | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
        creditLine: string | null;
        creditUrl: string | null;
      };
    }> | null;
  };
  eventMediaSubmission: {
    enabled: boolean | null;
    kicker: string | null;
    heading: string | null;
    explanation: string | null;
    ctaLabel: string | null;
    formUrl: string | null;
  } | null;
  merch: {
    kicker: string | null;
    heading: string;
    body: string | null;
    items: Array<{
      _key: string;
      item: {
        _id: string;
        name: string;
        description: string;
        priceDisplay: string | null;
        availabilityNote: string | null;
        image: {
          _id: string;
          title: string;
          alt: string | null;
          image: {
            asset: {
              _id: string;
              metadata: {
                dimensions: SanityImageDimensions | null;
              } | null;
            } | null;
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            _type: "image";
          } | null;
        } | null;
      };
    }> | null;
  };
  bookingCta: {
    kicker: string | null;
    heading: string;
    body: string;
    ctaLabel: string;
  };
  seo: {
    metaTitle: string | null;
    metaDescription: string | null;
    ogImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "homepage" && _id == "homepage"][0]{\n    hero,\n    heroVideo->{ videoUrl, videoProvider, title },\n    officialBandPhotos{\n      kicker,\n      heading,\n      body,\n      ctaLabel,\n      photos[]{\n        _key,\n        "mediaItem": @->{\n          _id,\n          title,\n          alt,\n          creditLine,\n          creditUrl,\n          image{\n            ...,\n            asset->{\n              _id,\n              metadata{ dimensions }\n            }\n          }\n        }\n      }\n    },\n    experience{\n      kicker,\n      heading,\n      introduction,\n      highlights[]{ _key, title, description }\n    },\n    upcomingShows{\n      kicker,\n      heading,\n      viewAllLabel,\n      emptyState{ title, message, actionLabel }\n    },\n    testimonialsIntro{ kicker, heading },\n    bookingCta,\n    newsletter{ kicker, heading, body, ctaLabel },\n    seo\n  }\n': HOMEPAGE_QUERY_RESULT;
    '\n  *[_type == "testimonial"]\n  | order(displayOrder asc, _id asc)[0...3] {\n    _id,\n    quote,\n    sourceName,\n    sourceContext,\n    sourceUrl,\n    displayOrder,\n    sourceLogo->{\n      _id,\n      title,\n      alt,\n      image{\n        ...,\n        asset->{\n          _id,\n          metadata{ dimensions }\n        }\n      }\n    }\n  }\n': TESTIMONIALS_QUERY_RESULT;
    '\n  *[_type == "aboutPage" && _id == "aboutPage"][0]{\n    intro{\n      kicker,\n      heading,\n      paragraphs,\n      heroImage->{\n        _id,\n        title,\n        alt,\n        image{\n          ...,\n          asset->{\n            _id,\n            metadata{ dimensions }\n          }\n        }\n      }\n    },\n    membersIntro{ kicker, heading, body },\n    members[]{\n      _key,\n      "member": @->{\n        _id,\n        name,\n        role,\n        profileImage->{\n          _id,\n          title,\n          alt,\n          image{\n            ...,\n            asset->{\n              _id,\n              metadata{ dimensions }\n            }\n          }\n        },\n        biography,\n        publicLinks[]{ _key, linkType, label, url }\n      }\n    },\n    testimonialsIntro{ kicker, heading },\n    bookingCta{ kicker, heading, body, ctaLabel },\n    seo{ metaTitle, metaDescription, ogImage }\n  }\n': ABOUT_PAGE_QUERY_RESULT;
    '\n  *[_type == "event"\n    && visibility == "public"\n    && status == "scheduled"\n    && coalesce(endDateTime, startDateTime) >= now()\n  ] | order(startDateTime asc) [0...3] {\n    _id, title, slug, startDateTime, endDateTime,\n    venue, location, externalEventUrl\n  }\n': UPCOMING_PUBLIC_EVENTS_QUERY_RESULT;
    '\n  *[_type == "showsPage" && _id == "showsPage"][0]{\n    intro{ kicker, heading, paragraphs },\n    upcoming{ heading },\n    recent{ kicker, heading },\n    emptyState{ title, message, actionLabel },\n    bookingCta{ kicker, heading, body, ctaLabel },\n    seo{ metaTitle, metaDescription, ogImage }\n  }\n': SHOWS_PAGE_QUERY_RESULT;
    '\n  *[\n    _type == "event"\n    && visibility == "public"\n    && defined(startDateTime)\n    && coalesce(endDateTime, startDateTime) >= now()\n  ]\n  | order(startDateTime asc, _id asc) {\n    _id,\n    "kind": "public",\n    status,\n    startDateTime,\n    endDateTime,\n    title,\n    venue,\n    location,\n    description,\n    externalEventUrl\n  }\n': SHOWS_UPCOMING_PUBLIC_EVENTS_QUERY_RESULT;
    '\n  *[\n    _type == "event"\n    && visibility == "busyOnly"\n    && status == "scheduled"\n    && defined(startDateTime)\n    && coalesce(endDateTime, startDateTime) >= now()\n  ]\n  | order(startDateTime asc, _id asc) {\n    _id,\n    "kind": "private",\n    startDateTime,\n    endDateTime\n  }\n': SHOWS_UPCOMING_PRIVATE_EVENTS_QUERY_RESULT;
    '\n  *[\n    _type == "event"\n    && visibility == "public"\n    && status == "scheduled"\n    && defined(startDateTime)\n    && coalesce(endDateTime, startDateTime) < now()\n  ]\n  | order(startDateTime desc, _id asc) [0...12] {\n    _id,\n    "kind": "public",\n    status,\n    startDateTime,\n    endDateTime,\n    title,\n    venue,\n    location,\n    description,\n    externalEventUrl\n  }\n': SHOWS_RECENT_PUBLIC_EVENTS_QUERY_RESULT;
    '\n  *[_type == "contactPage" && _id == "contactPage"][0]{\n    intro{ kicker, heading, lede, explanation },\n    newsletterCta{ heading, body, linkLabel },\n    faq[]{ _key, question, answer },\n    seo{ metaTitle, metaDescription, ogImage }\n  }\n': CONTACT_PAGE_QUERY_RESULT;
    '\n  *[_type == "musicPage" && _id == "musicPage"][0]{\n    featured{\n      kicker,\n      heading,\n      video->{\n        videoUrl,\n        videoProvider,\n        title\n      }\n    },\n    labelAffiliation{\n      kicker,\n      text,\n      logoAlt,\n      url,\n      missionStatement,\n      socialLinks{ facebookUrl, instagramUrl, youtubeUrl }\n    },\n    releases[]{\n      _key,\n      "release": @->{\n        _id,\n        title,\n        "slug": slug.current,\n        releaseType,\n        state,\n        releaseDate,\n        coverArtwork->{\n          _id,\n          alt,\n          image{\n            ...,\n            asset->{\n              _id,\n              metadata{ dimensions }\n            }\n          }\n        },\n        description,\n        spotifyUrl,\n        appleMusicUrl,\n        preSaveUrl,\n        watchVideoUrl\n      }\n    },\n    seo{ metaTitle, metaDescription, ogImage }\n  }\n': MUSIC_PAGE_QUERY_RESULT;
    '\n  *[_type == "galleryPage" && _id == "galleryPage"][0]{\n    gallery{\n      kicker,\n      heading,\n      body,\n      items[]{\n        _key,\n        "media": @->{\n          _id,\n          title,\n          alt,\n          category,\n          creditLine,\n          creditUrl,\n          image{\n            ...,\n            asset->{\n              _id,\n              metadata{ dimensions }\n            }\n          }\n        }\n      },\n      videos[]{\n        _key,\n        "media": @->{\n          _id,\n          title,\n          mediaType,\n          videoProvider,\n          videoUrl,\n          videoPoster{\n            ...,\n            asset->{\n              _id,\n              metadata{ dimensions }\n            }\n          },\n          creditLine,\n          creditUrl\n        }\n      }\n    },\n    eventMediaSubmission{\n      enabled,\n      kicker,\n      heading,\n      explanation,\n      ctaLabel,\n      formUrl\n    },\n    merch{\n      kicker,\n      heading,\n      body,\n      items[]{\n        _key,\n        "item": @->{\n          _id,\n          name,\n          description,\n          priceDisplay,\n          availabilityNote,\n          image->{\n            _id,\n            title,\n            alt,\n            image{\n              ...,\n              asset->{\n                _id,\n                metadata{ dimensions }\n              }\n            }\n          }\n        }\n      }\n    },\n    bookingCta{ kicker, heading, body, ctaLabel },\n    seo{ metaTitle, metaDescription, ogImage }\n  }\n': GALLERY_PAGE_QUERY_RESULT;
  }
}
